{
 "title": "Ambassador Modify",
 "description": "Ambassador dashboard for Prometheus",
 "tags": [ "ambassador" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "listener_port", "label": "Listener port", "query": "${VAR_LISTENER_PORT}" }
  ]
 },
 "panels": [
  {
   "title": "Ambassador Metrics Endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ambassador Response Codes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"2\"}[1m]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"3\"}[1m]))",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"4\"}[1m]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\"}[1m]))",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "API Response Codes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"2\"}[1m]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"3\"}[1m]))",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"4\"}[1m]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\"}[1m]))",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "Downstream Connections Length",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "Milliseconds" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_http_downstream_cx_length_ms_bucket[5m])) by (le))",
       "legendFormat": "95 percentile"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(envoy_http_downstream_cx_length_ms_bucket[5m])) by (le))",
       "legendFormat": "90th percentile"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_cx_length_ms_bucket[5m])) by (le))",
       "legendFormat": "50th percentile"
      },
      {}
     ]
    },
    {
     "title": "Active Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "RPM" }
     ],
     "targets": [
      {
       "expr": "sum(increase(envoy_http_downstream_cx_http1_active[1m]))",
       "legendFormat": "HTTP/1"
      },
      {
       "expr": "sum(increase(envoy_http_downstream_cx_http2_active_active[1m]))",
       "legendFormat": "HTTP/2"
      },
      {
       "expr": "sum(increase(envoy_http_downstream_cx_upgrades_active[1m]))",
       "legendFormat": "Websocket"
      }
     ]
    },
    {
     "title": "Registered Services",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(envoy_cluster_manager_active_clusters)"
      }
     ]
    }
   ]
  },
  { "title": "Ambassador Stats Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "API Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_listener_0_0_0_0_${listener_port}_http_ingress_http_downstream_rq_2xx[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(envoy_listener_0_0_0_0_${listener_port}_http_ingress_http_downstream_rq_3xx[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(envoy_listener_0_0_0_0_${listener_port}_http_ingress_http_downstream_rq_4xx[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(envoy_listener_0_0_0_0_${listener_port}_http_ingress_http_downstream_rq_5xx[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Downstream Connections Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "envoy_listener_0_0_0_0_${listener_port}_downstream_cx_length_ms{quantile=\"0.5\"}",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "envoy_listener_0_0_0_0_${listener_port}_downstream_cx_length_ms{quantile=\"0.9\"}",
     "legendFormat": "0.9 quantile"
    },
    {
     "expr": "envoy_listener_0_0_0_0_${listener_port}_downstream_cx_length_ms{quantile=\"0.99\"}",
     "legendFormat": "0.99 quantile"
    }
   ]
  },
  {
   "title": "Downstream Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_ingress_http_downstream_cx_http1_total[1m]))",
     "legendFormat": "HTTP/1.1"
    },
    {
     "expr": "sum(increase(envoy_http_ingress_http_downstream_cx_http2_total[1m]))",
     "legendFormat": "HTTP/2"
    },
    {
     "expr": "sum(increase(envoy_http_ingress_http_downstream_cx_websocket_total[1m]))",
     "legendFormat": "WebSocket"
    }
   ]
  },
  {
   "title": "Registered Services",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "envoy_cluster_manager_total_clusters"
    }
   ]
  }
 ]
}